services:
  - type: web
    name: fretboard-server
    env: docker
    repo: https://github.com/yourusername/yourrepo
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: REDIS_HOST
        value: your-redis-host.onrender.com
      - key: REDIS_PORT
        value: 6379

databases:
  - name: fretboard-redis
    type: redis
    plan: free
