services:
  - type: web
    name: fretboard-server
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379

  - type: private
    name: redis
    env: docker
    image: redis:latest
    disk:
      name: redis-data
      mountPath: /data
