services:
  - type: web
    name: fretboard-server
    env: go
    buildCommand: go build -o app
    startCommand: ./app
    runtime: docker
    repo: https://github.com/henry0125xu/fretboard-server
    plan: free
    envVars:
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        sync: false
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: "off"
version: "1"
